# Generated by Django 5.0.2 on 2024-03-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m3activity1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="item",
            managers=[],
        ),
        migrations.AddField(
            model_name="item",
            name="item_show",
            field=models.BooleanField(default=True),
        ),
    ]
