# Generated by Django 5.0.2 on 2024-03-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m3activity1", "0002_alter_item_managers_item_item_show"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.IntegerField(max_length=1)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="item_quantity",
            field=models.IntegerField(default=1),
        ),
    ]
