# Generated by Django 5.0.2 on 2024-03-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m3activity1", "0003_order_item_item_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="itemOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.IntegerField()),
                ("order_id", models.IntegerField()),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=30)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.IntegerField(),
        ),
    ]
