# Generated by Django 5.0.2 on 2024-03-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("m3activity1", "0004_itemorder_alter_order_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="order",
        ),
    ]
