# Generated by Django 5.0.2 on 2024-03-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m3activity1", "0005_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.IntegerField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
