# Generated by Django 5.0.2 on 2024-03-16 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("m3activity1", "0009_orderesadasd_delete_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="orderesadasd",
            new_name="order",
        ),
    ]
