# Generated by Django 5.0.2 on 2024-03-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m3activity1", "0010_rename_orderesadasd_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemorder",
            name="item_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="m3activity1.item",
            ),
        ),
        migrations.AlterField(
            model_name="itemorder",
            name="order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="m3activity1.order",
            ),
        ),
    ]
