# Generated by Django 5.0.2 on 2024-04-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m3activity1", "0012_alter_itemorder_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_quantity",
            field=models.BigIntegerField(),
        ),
    ]
